sudo: required
services:
    - docker

before_install:
    - docker build -t tegain/docker-casts-ci -f Dockerfile.dev .

script:
    - docker run -e CI=true tegain/docker-casts-ci npm run test -- --coverage
